---
# EXPERIMENTAL PARAMETERS
COLLECT_LOGS : False
COLLECT_TRAINING_DATA : False
USE_INFERENCE_SERVER : False
RISK_MODEL : "digital" # "naive"  "manual", "digital", "transformer"
SHOULD_MODIFY_BEHAVIOR : True
USE_ORACLE: False

## INTERVENTIONS
INTERVENTION_DAY : 5 # NOTE: INTERVENTION is only valid if INTERVENTION_DAY >= 0
INTERVENTION : "Tracing"
PERCENT_FOLLOW : 1.0
P_HAS_APP : -1.0

# PATHS
TRANSFORMER_EXP_PATH: "" #"CTT-SHIPMENT-0"
CLUSTER_PATH : "output/"

# Inference & Training
INFECTIOUSNESS_N_DAYS_HISTORY : 14
TRACING_N_DAYS_HISTORY : 14
MP_BATCHSIZE : "auto"
MP_N_JOBS : "1"
MP_BACKEND : "loky"
DUMP_CLUSTERS : False
CLUSTER_TYPE : "heuristic" # "random", "graph"

# TRACING RISK MODEL PARAMETERS  (non-ML)
TRACE_SYMPTOMS : False
TRACE_RISK_UPDATE : False
TRACING_ORDER : 1
UPDATES_PER_DAY : 4

RISK_MAPPING: []
